name = input("Enter your name: ")
usn = input("Enter your usn: ")
marks1 = int(input("Etner your marks in first subject: "))
marks2 = int(input("Enter your marks in second subject: "))
marks3 = int(input("Enter your marks in third subject: "))
print("-------------------------")
print("Name : ",name)
print("USN : ",usn )
print("Marks1: ",marks1)
print("Marks2: ",marks2)
print("Marks3: ",marks3)
print("Total: ",marks1+marks2+marks3)
per = (marks1+marks2+marks3)/3
print("Total persent you got is : ",per,"%")
print("-------------------------")